// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR2ifkUmOONWhJosydY1mCIRu1Y0Eb7jQ',
    appId: '1:729976284153:web:ac504a7e75e67874789328',
    messagingSenderId: '729976284153',
    projectId: 'nice-rice-app',
    authDomain: 'nice-rice-app.firebaseapp.com',
    storageBucket: 'nice-rice-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYe64lgeT0JKDv_lvZC9rrOBvA2V4Gf8',
    appId: '1:729976284153:android:353c3b6bd270fd35789328',
    messagingSenderId: '729976284153',
    projectId: 'nice-rice-app',
    storageBucket: 'nice-rice-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxYpYP8No44HC0co4wNhHUH3mkIRhZXU',
    appId: '1:729976284153:ios:dbdb0bde16c0deb7789328',
    messagingSenderId: '729976284153',
    projectId: 'nice-rice-app',
    storageBucket: 'nice-rice-app.firebasestorage.app',
    iosBundleId: 'com.example.niceRice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNxYpYP8No44HC0co4wNhHUH3mkIRhZXU',
    appId: '1:729976284153:ios:dbdb0bde16c0deb7789328',
    messagingSenderId: '729976284153',
    projectId: 'nice-rice-app',
    storageBucket: 'nice-rice-app.firebasestorage.app',
    iosBundleId: 'com.example.niceRice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR2ifkUmOONWhJosydY1mCIRu1Y0Eb7jQ',
    appId: '1:729976284153:web:16f3fe97cefa4b23789328',
    messagingSenderId: '729976284153',
    projectId: 'nice-rice-app',
    authDomain: 'nice-rice-app.firebaseapp.com',
    storageBucket: 'nice-rice-app.firebasestorage.app',
  );
}
